language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

allow_failures:
  - php: hhvm-nightly
  - php: 7.0

before_script:
  - composer self-update
  - composer install --prefer-source --dev

script:
  - vendor/bin/phpspec run --format=pretty